do(
  try(
    do {  # Try
      try (
        do {
          throw(42)
        },
        do {
          print("Inner catch. Rethrowing..."),
          throw(__error__)
        }
      )
    },
    do {  # Catch
      print(+("Outer catch. ", __error__))
    }
  )
)
